### ISSUE TITLE
setup-LogPipeline Invalid WorkspaceSku

### ISSUE THREAD

**Issue by mathieu-meon-eu** [digitc1/AzLandingZone#101]
https://github.com/digitc1/AzLandingZone/blob/fe59a10f76af8b3e722ffd11ce0f824daaac62ee/AzLandingZone/Private/PowerShell/setup-LogPipeline.ps1#L19

The forced Sku parameter value "Standard" causes the following issue :
![image](https://user-images.githubusercontent.com/88720891/176876192-c1814e31-14a2-4f49-bc0f-118b9b60bcf1.png)

`Pricing tier doesn’t match the subscription’s billing model. Read [http://aka.ms/PricingTierWarning](https://aka.ms/PricingTierWarning) for more details`

Indeed, "Standard" is not anymore available in our subscription. The proper value should be the pay-as-you-go SKU whose value is "PerGB2018".

https://docs.microsoft.com/en-us/azure/templates/microsoft.operationalinsights/workspaces?tabs=json#workspacesku

**Comment by augustincolle-digit** [comment]
Resolved in version 1.17
