### ISSUE TITLE
Update information for CERT-EU

### ISSUE THREAD

**Issue by augustincolle-digit** [digitc1/AzLandingZone#115]
CERT-EU want to integrate with Sentinel and Lighthouse.
Update the script accordingly:
- update the -SOC "CERTEU" parameter
- Get the Lighthouse configuration from CERTEU
- Update code
- Event hub should remain possible for optional external SOC to integrate with Splunk

**Comment by barrjam** [comment]
Delete the following:

- https://github.com/digitc1/AzLandingZonePublic/blob/develop/definitions/lighthouse/definition-managedServices.json
- https://github.com/digitc1/AzLandingZonePublic/blob/develop/templates/delegatedResourceManagement.parameters.json
- https://github.com/digitc1/AzLandingZonePublic/blob/develop/templates/resourceManagement.parameters.json

Update

- https://github.com/digitc1/AzLandingZone/blob/develop/AzLandingZone/Private/rest-api/subscriptions/Register-LzManagedServicesDefinition.ps1
